apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lwcluster
  region: ap-south-1

nodeGroups:
  - name: ng1
    desiredCapacity: 1
    instanceType: t2.micro
    ssh:
        publicKeyName: ec2_key
  - name: ng2
    desiredCapacity: 1
    instanceType: t2.micro
    ssh:
        publicKeyName: ec2_key
  - name: ng3
    minSize: 1
    maxSize: 3
    ssh:
        publicKeyName: ec2_key
    instancesDistribution:
      maxPrice: 0.017
      instanceTypes: ["t2.micro"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 2
